### PR TITLE
Updated result count from 197 to 218 for problem #13

### PR DESCRIPTION
**Pull request by JoeKarlsson1**

### CODE REVIEW

**Comment by jaywon** [comment]
I'd like to merge this but I've had little exposure to this exercise but I know there's been conversation around this before as to proper count. @theRemix can you clarify and merge if correct?

**Comment by JoeKarlsson1** [comment]
This is still a problem - I am positive that `218` is the correct solution. Can we merge it or write an amendment to allow for `218` or `197`?

**Comment by javenkn** [comment]
@theRemix @jaywon 
Individually there are 118 for firewall and nemo, 105 for ssl and nemo, and an overlap of 5 for firewall and ssl and nemo. That comes out to 218.  (118 - 5 = 113) + (105 - 5 = 100) + 5 = `218`.
``` sql
SELECT COUNT(*)
  FROM posts
  INNER JOIN users ON posts.user_id = users.id
  INNER JOIN comments ON posts.id = comments.post_id
  WHERE (lower(comments.body) LIKE '%firewall%')
  AND (lower(posts.content) LIKE '%nemo%');

count
-------
   118
(1 row)

SELECT COUNT(*)
  FROM posts
  INNER JOIN users ON posts.user_id = users.id
  INNER JOIN comments ON posts.id = comments.post_id
  WHERE (lower(comments.body) LIKE '%ssl%')
  AND (lower(posts.content) LIKE '%nemo%');

 count
-------
   105
(1 row)

SELECT COUNT(*)
  FROM posts
  INNER JOIN users ON posts.user_id = users.id
  INNER JOIN comments ON posts.id = comments.post_id
  WHERE (lower(comments.body) LIKE '%ssl%' AND lower(comments.body) LIKE '%firewall%')
  AND (lower(posts.content) LIKE '%nemo%');

 count
-------
     5
(1 row)
```

**Comment by sgnl** [comment]
Based on the post by @javenkn and input from @thgaskell I'm going to go ahead and merge this.

**Pull request merged**
